apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mynginxchart.fullname" . }}
  labels:
    {{- include "mynginxchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mynginxchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mynginxchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:latest"
          ports:
            - containerPort: 80

